
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 5;
  public static final int MULTIPLICACION = 7;
  public static final int DOSPUNTOS = 16;
  public static final int CORCHETEC = 13;
  public static final int CORCHETEA = 12;
  public static final int DECIMAL = 3;
  public static final int DIVISION = 6;
  public static final int ETIQUETAS = 24;
  public static final int EJECUTAR = 32;
  public static final int LLAVEC = 11;
  public static final int ID = 33;
  public static final int LLAVEA = 10;
  public static final int COMILLAS = 14;
  public static final int PORCENTAJE = 29;
  public static final int TIPO = 27;
  public static final int VALORES = 25;
  public static final int BARRAS = 19;
  public static final int COMA = 15;
  public static final int TOTAL = 30;
  public static final int EOF = 0;
  public static final int DEF = 18;
  public static final int PIE = 20;
  public static final int EXTRA = 31;
  public static final int CANTIDAD = 28;
  public static final int error = 1;
  public static final int EJEY = 23;
  public static final int PUNTOCOMA = 17;
  public static final int EJEX = 22;
  public static final int ENTERO = 2;
  public static final int UNIR = 26;
  public static final int PARENTESISC = 9;
  public static final int TITULO = 21;
  public static final int MAS = 4;
  public static final int PARENTESISA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "MULTIPLICACION",
  "PARENTESISA",
  "PARENTESISC",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "COMILLAS",
  "COMA",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "CANTIDAD",
  "PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "ID"
  };
}

